"use strict";
/* 현재 스트레스 40 이상에서 여는 핸드폰 — 3종의 짧은 스테이지와 균등한 회복 보상 */
(function(){
  const el={},held=Object.create(null),STAGE_HEAL=20; let current=null,ready=false;
  const dodge={x:50,time:10,greenHeal:0,spawn:0,items:[],cleared:false};
  const puzzle={matched:new Set(),cleared:false};
  const soul={x:50,y:78,hp:3,time:8,inv:0,spawn:0,hazards:[],cleared:false};
  const shapes=[{id:'circle',glyph:'●',name:'동그라미'},{id:'triangle',glyph:'▲',name:'세모'},{id:'square',glyph:'■',name:'네모'},{id:'diamond',glyph:'◆',name:'마름모'}];
  function cache(){if(ready)return;['phoneOverlay','phoneQuickBtn','phoneHomeBtn','phoneCloseBtn','phoneTitle','phoneHome','phoneResult','phoneResultTitle','phoneResultText','phoneResultConfirm','gameDodge','gamePuzzle','gameSoul','dodgeField','dodgePlayer','dodgeTime','dodgeHeal','puzzleBoard','puzzleTargets','puzzlePieces','puzzleScore','puzzleState','puzzleReset','soulField','soulPlayer','soulTime','soulHp'].forEach(id=>el[id]=document.getElementById(id));el.phoneQuickBtn.addEventListener('click',toggle);el.phoneCloseBtn.addEventListener('click',()=>close(false));el.phoneHomeBtn.addEventListener('click',showHome);el.phoneResultConfirm.addEventListener('click',()=>{hideResult();showHome();});document.querySelectorAll('.gameApp').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.game)));el.puzzleReset.addEventListener('click',resetPuzzleStage);el.dodgeField.addEventListener('pointerdown',moveDodgePointer);el.dodgeField.addEventListener('pointermove',e=>{if(e.buttons&1)moveDodgePointer(e);});ready=true;renderPuzzle();showHome();}
  function playable(){return G.state===GameState.TRAVELING||G.state===GameState.SEAT_RUSH||G.state===GameState.BOARDING;}
  function updateUnlock(){const available=G.stress>=BALANCE.phoneUnlockStress;if(available&&!G.phoneUnlocked&&!G.phoneUnlockNotified){G.phoneUnlockNotified=true;showCenter('📱 스트레스 40! P키로 짧은 미니게임을 열 수 있습니다.',false,3);}G.phoneUnlocked=available;el.phoneQuickBtn.disabled=!available||!playable();el.phoneQuickBtn.classList.toggle('ready',available&&playable());}
  function toggle(){cache();if(G.phoneOpen){close(false);return;}if(G.stress<BALANCE.phoneUnlockStress){showCenter('핸드폰은 현재 스트레스가 40 이상일 때만 열 수 있습니다.',true,1.5);return;}if(!playable()||G.state===GameState.EVENT)return;G.phoneOpen=true;G.pointerHeld=false;leftMouseDown=false;el.phoneOverlay.classList.remove('hidden');el.phoneOverlay.setAttribute('aria-hidden','false');document.body.classList.add('phone-open');}
  function close(force){cache();G.phoneOpen=false;Object.keys(held).forEach(k=>held[k]=false);el.phoneOverlay.classList.add('hidden');el.phoneOverlay.setAttribute('aria-hidden','true');document.body.classList.remove('phone-open');if(force)showHome();}
  function hideResult(){el.phoneResult.classList.add('hidden');}
  function showHome(){current=null;hideResult();document.querySelectorAll('.phonePage').forEach(p=>p.classList.remove('active'));el.phoneHome.classList.add('active');el.phoneTitle.textContent='퇴근 탈출구';el.phoneHomeBtn.style.visibility='hidden';}
  function openGame(name){current=name;document.querySelectorAll('.phonePage').forEach(p=>p.classList.remove('active'));const n={dodge:['gameDodge','상사 문자 피하기'],puzzle:['gamePuzzle','퇴근 퍼즐'],soul:['gameSoul','퇴근 의지']}[name];el[n[0]].classList.add('active');el.phoneTitle.textContent=n[1];el.phoneHomeBtn.style.visibility='visible';if(name==='dodge'&&dodge.cleared)resetDodgeStage();if(name==='puzzle'&&puzzle.cleared)resetPuzzleStage();if(name==='soul'&&soul.cleared)resetSoulStage();}
  function keyDown(k){held[k]=true;}function keyUp(k){held[k]=false;}
  function stageClear(game,bonus){heal(Math.max(0,bonus));game.cleared=true;current=null;el.phoneResultTitle.textContent='스테이지 클리어!';el.phoneResultText.textContent='스트레스가 '+STAGE_HEAL+' 감소했습니다.';el.phoneResult.classList.remove('hidden');el.phoneTitle.textContent='클리어 결과';el.phoneHomeBtn.style.visibility='hidden';}
  function moveDodgePointer(e){const r=el.dodgeField.getBoundingClientRect();dodge.x=Math.max(7,Math.min(93,(e.clientX-r.left)/r.width*100));}
  function spawnMessage(){const green=Math.random()<.38,node=document.createElement('div');node.className='fallingMessage '+(green?'good':'bad');node.textContent=green?'친구: 저녁 먹자!':['오늘까지 가능?','긴급 업무','퇴근 전 회신'][Math.floor(Math.random()*3)];const m={x:10+Math.random()*80,y:-10,speed:38+Math.random()*18,green,node};node.style.left=m.x+'%';el.dodgeField.appendChild(node);dodge.items.push(m);}
  function updateDodge(dt){if(dodge.cleared)return;const dir=(held.arrowleft||held.a?-1:0)+(held.arrowright||held.d?1:0);dodge.x=Math.max(7,Math.min(93,dodge.x+dir*75*dt));dodge.time=Math.max(0,dodge.time-dt);dodge.spawn-=dt;if(dodge.spawn<=0){spawnMessage();dodge.spawn=.48;}for(let i=dodge.items.length-1;i>=0;i--){const m=dodge.items[i];m.y+=m.speed*dt;m.node.style.top=m.y+'%';if(m.y>76&&m.y<96&&Math.abs(m.x-dodge.x)<15){if(m.green&&dodge.greenHeal<6){heal(2);dodge.greenHeal+=2;}else if(!m.green)damage(2);m.node.remove();dodge.items.splice(i,1);continue;}if(m.y>105){m.node.remove();dodge.items.splice(i,1);}}el.dodgePlayer.style.left=dodge.x+'%';el.dodgeTime.textContent=dodge.time.toFixed(1);el.dodgeHeal.textContent=dodge.greenHeal;if(dodge.time<=0)stageClear(dodge,STAGE_HEAL-dodge.greenHeal);}
  function resetDodgeStage(){dodge.items.forEach(m=>m.node.remove());dodge.items=[];dodge.x=50;dodge.time=10;dodge.greenHeal=0;dodge.spawn=0;dodge.cleared=false;el.dodgeTime.textContent='10.0';el.dodgeHeal.textContent='0';}
  function renderPuzzle(){if(!el.puzzleTargets)return;el.puzzleTargets.innerHTML='';el.puzzlePieces.innerHTML='';const order=shapes.slice().sort(()=>Math.random()-.5);shapes.forEach(s=>{const t=document.createElement('div');t.className='shapeTarget '+s.id;t.dataset.shape=s.id;t.innerHTML='<span>'+s.glyph+'</span><small>'+s.name+'</small>';t.addEventListener('dragover',e=>e.preventDefault());t.addEventListener('drop',e=>{e.preventDefault();matchShape(e.dataTransfer.getData('text/plain'),s.id);});el.puzzleTargets.appendChild(t);});order.forEach(s=>{if(puzzle.matched.has(s.id))return;const p=document.createElement('div');p.className='shapePiece '+s.id;p.draggable=true;p.dataset.shape=s.id;p.textContent=s.glyph;p.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',s.id));p.addEventListener('pointerdown',()=>{el.puzzlePieces.dataset.selected=s.id;document.querySelectorAll('.shapePiece').forEach(x=>x.classList.toggle('selected',x===p));});el.puzzlePieces.appendChild(p);});el.puzzleTargets.querySelectorAll('.shapeTarget').forEach(t=>t.addEventListener('pointerup',()=>{const selected=el.puzzlePieces.dataset.selected;if(selected)matchShape(selected,t.dataset.shape);}));el.puzzleScore.textContent=puzzle.matched.size;el.puzzleState.textContent=puzzle.cleared?'클리어!':'같은 모양에 놓기';}
  function matchShape(piece,target){if(!piece||piece!==target||puzzle.matched.has(piece))return;puzzle.matched.add(piece);el.puzzlePieces.dataset.selected='';if(puzzle.matched.size>=shapes.length){puzzle.cleared=true;renderPuzzle();stageClear(puzzle,STAGE_HEAL);}else renderPuzzle();}
  function resetPuzzleStage(){puzzle.matched.clear();puzzle.cleared=false;renderPuzzle();}
  function spawnSoulHazard(){const node=document.createElement('div');node.className='soulHazard';const h={x:5+Math.random()*90,y:-5,vx:(Math.random()-.5)*22,vy:40+Math.random()*22,node};node.style.left=h.x+'%';el.soulField.appendChild(node);soul.hazards.push(h);}
  function resetSoulStage(){soul.hazards.forEach(h=>h.node.remove());soul.hazards=[];soul.x=50;soul.y=78;soul.hp=3;soul.time=8;soul.inv=.6;soul.spawn=0;soul.cleared=false;}
  function updateSoul(dt){if(soul.cleared)return;const dx=(held.arrowleft||held.a?-1:0)+(held.arrowright||held.d?1:0),dy=(held.arrowup||held.w?-1:0)+(held.arrowdown||held.s?1:0);soul.x=Math.max(5,Math.min(95,soul.x+dx*62*dt));soul.y=Math.max(7,Math.min(93,soul.y+dy*62*dt));soul.time=Math.max(0,soul.time-dt);soul.inv=Math.max(0,soul.inv-dt);soul.spawn-=dt;if(soul.spawn<=0){spawnSoulHazard();soul.spawn=.55;}for(let i=soul.hazards.length-1;i>=0;i--){const h=soul.hazards[i];h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<3||h.x>97)h.vx*=-1;h.node.style.left=h.x+'%';h.node.style.top=h.y+'%';if(soul.inv<=0&&Math.hypot(h.x-soul.x,h.y-soul.y)<8){soul.hp--;soul.inv=.8;h.node.remove();soul.hazards.splice(i,1);if(soul.hp<=0){showCenter('하트가 부서졌습니다. 짧은 스테이지를 다시 시작합니다.',true,1.4);resetSoulStage();}continue;}if(h.y>105){h.node.remove();soul.hazards.splice(i,1);}}el.soulPlayer.style.left=soul.x+'%';el.soulPlayer.style.top=soul.y+'%';el.soulPlayer.classList.toggle('invincible',soul.inv>0);el.soulTime.textContent=soul.time.toFixed(1);el.soulHp.textContent=soul.hp;if(soul.time<=0)stageClear(soul,STAGE_HEAL);}
  function update(dt){cache();updateUnlock();if(!G.phoneOpen||!current)return;if(current==='dodge')updateDodge(dt);else if(current==='soul')updateSoul(dt);}
  function reset(){cache();close(true);resetDodgeStage();resetPuzzleStage();resetSoulStage();}
  window.addEventListener('keyup',e=>keyUp(e.key.toLowerCase()));window.PhoneMiniGames={update,toggle,close,reset,keyDown,keyUp};
})();
