"use strict";
/* 현재 스트레스 40 이상에서 여는 핸드폰 — 3종의 짧은 스테이지와 균등한 회복 보상 */
(function(){
  const el={},held=Object.create(null),STAGE_HEAL=20; let current=null,ready=false;
  const dodge={x:50,time:10,greenHeal:0,spawn:0,items:[],cleared:false};
  const puzzle={grid:[1,0,0,0,2,0,0,0,3],fixed:new Set([0,4,8]),selected:0,cleared:false};
  const soul={x:50,y:78,hp:3,time:8,inv:0,spawn:0,hazards:[],cleared:false};
  function cache(){if(ready)return;['phoneOverlay','phoneQuickBtn','phoneHomeBtn','phoneCloseBtn','phoneTitle','phoneHome','phoneResult','phoneResultTitle','phoneResultText','phoneResultConfirm','gameDodge','gamePuzzle','gameSoul','dodgeField','dodgePlayer','dodgeTime','dodgeHeal','puzzleBoard','puzzleNumberTray','puzzleScore','puzzleState','puzzleReset','soulField','soulPlayer','soulTime','soulHp'].forEach(id=>el[id]=document.getElementById(id));el.phoneQuickBtn.addEventListener('click',toggle);el.phoneCloseBtn.addEventListener('click',()=>close(false));el.phoneHomeBtn.addEventListener('click',showHome);el.phoneResultConfirm.addEventListener('click',()=>{hideResult();showHome();});document.querySelectorAll('.gameApp').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.game)));el.puzzleReset.addEventListener('click',resetPuzzleStage);el.puzzleBoard.addEventListener('dragover',handleSudokuDragOver);el.puzzleBoard.addEventListener('dragleave',handleSudokuDragLeave);el.puzzleBoard.addEventListener('drop',handleSudokuDrop);el.puzzleBoard.addEventListener('pointerup',handleSudokuPointerPlace);el.puzzleNumberTray.querySelectorAll('.numberTile').forEach(tile=>{tile.addEventListener('dragstart',e=>{puzzle.selected=Number(tile.dataset.number);e.dataTransfer.setData('text/plain',tile.dataset.number);tile.classList.add('dragging');});tile.addEventListener('dragend',()=>tile.classList.remove('dragging'));tile.addEventListener('pointerdown',()=>selectSudokuNumber(Number(tile.dataset.number)));});el.dodgeField.addEventListener('pointerdown',moveDodgePointer);el.dodgeField.addEventListener('pointermove',e=>{if(e.buttons&1)moveDodgePointer(e);});['pointerdown','pointermove','pointerup','pointercancel','click','contextmenu'].forEach(type=>el.gameSoul.addEventListener(type,blockSoulPointer,{capture:true}));ready=true;renderPuzzle();showHome();}
  function playable(){return G.state===GameState.TRAVELING||G.state===GameState.SEAT_RUSH||G.state===GameState.BOARDING;}
  function updateUnlock(){const available=G.stress>=BALANCE.phoneUnlockStress;if(available&&!G.phoneUnlocked&&!G.phoneUnlockNotified){G.phoneUnlockNotified=true;showCenter('📱 스트레스 40! P키로 짧은 미니게임을 열 수 있습니다.',false,3);}G.phoneUnlocked=available;el.phoneQuickBtn.disabled=!available||!playable();el.phoneQuickBtn.classList.toggle('ready',available&&playable());}
  function toggle(){cache();if(G.phoneOpen){close(false);return;}if(G.stress<BALANCE.phoneUnlockStress){showCenter('핸드폰은 현재 스트레스가 40 이상일 때만 열 수 있습니다.',true,1.5);return;}if(!playable()||G.state===GameState.EVENT)return;G.phoneOpen=true;G.pointerHeld=false;leftMouseDown=false;el.phoneOverlay.classList.remove('hidden');el.phoneOverlay.setAttribute('aria-hidden','false');document.body.classList.add('phone-open');}
  function close(force){cache();G.phoneOpen=false;Object.keys(held).forEach(k=>held[k]=false);el.phoneOverlay.classList.add('hidden');el.phoneOverlay.setAttribute('aria-hidden','true');document.body.classList.remove('phone-open');if(force)showHome();}
  function hideResult(){el.phoneResult.classList.add('hidden');}
  function showHome(){current=null;hideResult();document.querySelectorAll('.phonePage').forEach(p=>p.classList.remove('active'));el.phoneHome.classList.add('active');el.phoneTitle.textContent='퇴근 탈출구';el.phoneHomeBtn.style.visibility='hidden';}
  function openGame(name){current=name;document.querySelectorAll('.phonePage').forEach(p=>p.classList.remove('active'));const n={dodge:['gameDodge','상사 문자 피하기'],puzzle:['gamePuzzle','3×3 미니 스도쿠'],soul:['gameSoul','퇴근 의지']}[name];el[n[0]].classList.add('active');el.phoneTitle.textContent=n[1];el.phoneHomeBtn.style.visibility='visible';if(name==='dodge'&&dodge.cleared)resetDodgeStage();if(name==='puzzle'&&puzzle.cleared)resetPuzzleStage();if(name==='soul'&&soul.cleared)resetSoulStage();}
  function keyDown(k){held[k]=true;}function keyUp(k){held[k]=false;}
  // 퇴근 의지는 키보드 전용이다. 게임 영역의 클릭/드래그/터치/우클릭 메뉴를 모두 차단한다.
  // 헤더의 닫기/뒤로가기 버튼은 gameSoul 바깥에 있으므로 계속 사용할 수 있다.
  function blockSoulPointer(e){e.preventDefault();e.stopPropagation();}
  function stageClear(game,bonus){heal(Math.max(0,bonus));game.cleared=true;current=null;el.phoneResultTitle.textContent='스테이지 클리어!';el.phoneResultText.textContent='스트레스가 '+STAGE_HEAL+' 감소했습니다.';el.phoneResult.classList.remove('hidden');el.phoneTitle.textContent='클리어 결과';el.phoneHomeBtn.style.visibility='hidden';}
  function moveDodgePointer(e){const r=el.dodgeField.getBoundingClientRect();dodge.x=Math.max(7,Math.min(93,(e.clientX-r.left)/r.width*100));}
  function spawnMessage(){const green=Math.random()<.38,node=document.createElement('div');node.className='fallingMessage '+(green?'good':'bad');node.textContent=green?'친구: 저녁 먹자!':['오늘까지 가능?','긴급 업무','퇴근 전 회신'][Math.floor(Math.random()*3)];const m={x:10+Math.random()*80,y:-10,speed:38+Math.random()*18,green,node};node.style.left=m.x+'%';el.dodgeField.appendChild(node);dodge.items.push(m);}
  function updateDodge(dt){if(dodge.cleared)return;const dir=(held.arrowleft||held.a?-1:0)+(held.arrowright||held.d?1:0);dodge.x=Math.max(7,Math.min(93,dodge.x+dir*75*dt));dodge.time=Math.max(0,dodge.time-dt);dodge.spawn-=dt;if(dodge.spawn<=0){spawnMessage();dodge.spawn=.48;}for(let i=dodge.items.length-1;i>=0;i--){const m=dodge.items[i];m.y+=m.speed*dt;m.node.style.top=m.y+'%';if(m.y>76&&m.y<96&&Math.abs(m.x-dodge.x)<15){if(m.green&&dodge.greenHeal<6){heal(2);dodge.greenHeal+=2;}else if(!m.green)damage(2);m.node.remove();dodge.items.splice(i,1);continue;}if(m.y>105){m.node.remove();dodge.items.splice(i,1);}}el.dodgePlayer.style.left=dodge.x+'%';el.dodgeTime.textContent=dodge.time.toFixed(1);el.dodgeHeal.textContent=dodge.greenHeal;if(dodge.time<=0)stageClear(dodge,STAGE_HEAL-dodge.greenHeal);}
  function resetDodgeStage(){dodge.items.forEach(m=>m.node.remove());dodge.items=[];dodge.x=50;dodge.time=10;dodge.greenHeal=0;dodge.spawn=0;dodge.cleared=false;el.dodgeTime.textContent='10.0';el.dodgeHeal.textContent='0';}
  function renderPuzzle(){if(!el.puzzleBoard)return;el.puzzleBoard.innerHTML='';puzzle.grid.forEach((value,index)=>{const cell=document.createElement('div');cell.className='sudokuCell'+(puzzle.fixed.has(index)?' fixed':'');cell.dataset.index=index;cell.textContent=value||'';cell.setAttribute('aria-label',(puzzle.fixed.has(index)?'고정 숫자 ':'숫자를 놓을 칸 ')+(index+1));el.puzzleBoard.appendChild(cell);});el.puzzleScore.textContent=puzzle.grid.filter(Boolean).length;el.puzzleState.textContent=puzzle.cleared?'클리어!':(puzzle.grid.every(Boolean)?'행과 열을 확인하세요':'숫자를 드래그해 채우세요');}
  function selectSudokuNumber(number){puzzle.selected=number;el.puzzleNumberTray.querySelectorAll('.numberTile').forEach(tile=>tile.classList.toggle('selected',Number(tile.dataset.number)===number));}
  function handleSudokuDragOver(e){const cell=e.target.closest('.sudokuCell');if(!cell||puzzle.fixed.has(Number(cell.dataset.index))||puzzle.cleared)return;e.preventDefault();cell.classList.add('dropReady');}
  function handleSudokuDragLeave(e){const cell=e.target.closest('.sudokuCell');if(cell)cell.classList.remove('dropReady');}
  function handleSudokuDrop(e){e.preventDefault();const cell=e.target.closest('.sudokuCell');const number=Number(e.dataTransfer.getData('text/plain'))||puzzle.selected;placeSudokuNumber(cell,number);}
  function handleSudokuPointerPlace(e){const cell=e.target.closest('.sudokuCell');if(cell&&puzzle.selected)placeSudokuNumber(cell,puzzle.selected);}
  function placeSudokuNumber(cell,number){if(!cell||!number||puzzle.cleared)return;const index=Number(cell.dataset.index);if(puzzle.fixed.has(index))return;puzzle.grid[index]=number;checkSudoku();}
  function checkSudoku(){const validGroup=values=>values.slice().sort().join('')==='123';let solved=puzzle.grid.every(Boolean);for(let row=0;row<3&&solved;row++)solved=validGroup(puzzle.grid.slice(row*3,row*3+3));for(let col=0;col<3&&solved;col++)solved=validGroup([puzzle.grid[col],puzzle.grid[col+3],puzzle.grid[col+6]]);if(solved){puzzle.cleared=true;renderPuzzle();stageClear(puzzle,STAGE_HEAL);}else renderPuzzle();}
  function resetPuzzleStage(){const solutions=[[1,2,3,2,3,1,3,1,2],[1,3,2,2,1,3,3,2,1],[2,1,3,3,2,1,1,3,2]];const solution=solutions[Math.floor(Math.random()*solutions.length)];const fixedOptions=[[0,4,8],[1,3,8],[2,4,6],[0,5,7]];const fixed=fixedOptions[Math.floor(Math.random()*fixedOptions.length)];puzzle.fixed=new Set(fixed);puzzle.grid=solution.map((value,index)=>puzzle.fixed.has(index)?value:0);puzzle.selected=0;puzzle.cleared=false;if(el.puzzleNumberTray)el.puzzleNumberTray.querySelectorAll('.numberTile').forEach(tile=>tile.classList.remove('selected'));renderPuzzle();}
  function spawnSoulHazard(){const node=document.createElement('div');node.className='soulHazard';const h={x:5+Math.random()*90,y:-5,vx:(Math.random()-.5)*22,vy:40+Math.random()*22,node};node.style.left=h.x+'%';el.soulField.appendChild(node);soul.hazards.push(h);}
  function resetSoulStage(){soul.hazards.forEach(h=>h.node.remove());soul.hazards=[];soul.x=50;soul.y=78;soul.hp=3;soul.time=8;soul.inv=.6;soul.spawn=0;soul.cleared=false;}
  function updateSoul(dt){if(soul.cleared)return;const dx=(held.arrowleft||held.a?-1:0)+(held.arrowright||held.d?1:0),dy=(held.arrowup||held.w?-1:0)+(held.arrowdown||held.s?1:0);soul.x=Math.max(5,Math.min(95,soul.x+dx*68*dt));soul.y=Math.max(7,Math.min(93,soul.y+dy*68*dt));soul.time=Math.max(0,soul.time-dt);soul.inv=Math.max(0,soul.inv-dt);soul.spawn-=dt;if(soul.spawn<=0){spawnSoulHazard();soul.spawn=.55;}for(let i=soul.hazards.length-1;i>=0;i--){const h=soul.hazards[i];h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<3||h.x>97)h.vx*=-1;h.node.style.left=h.x+'%';h.node.style.top=h.y+'%';if(soul.inv<=0&&Math.hypot(h.x-soul.x,h.y-soul.y)<8){soul.hp--;soul.inv=.8;h.node.remove();soul.hazards.splice(i,1);if(soul.hp<=0){showCenter('하트가 부서졌습니다. 짧은 스테이지를 다시 시작합니다.',true,1.4);resetSoulStage();}continue;}if(h.y>105){h.node.remove();soul.hazards.splice(i,1);}}el.soulPlayer.style.left=soul.x+'%';el.soulPlayer.style.top=soul.y+'%';el.soulPlayer.classList.toggle('invincible',soul.inv>0);el.soulTime.textContent=soul.time.toFixed(1);el.soulHp.textContent=soul.hp;if(soul.time<=0)stageClear(soul,STAGE_HEAL);}
  function update(dt){cache();updateUnlock();if(!G.phoneOpen||!current)return;if(current==='dodge')updateDodge(dt);else if(current==='soul')updateSoul(dt);}
  function reset(){cache();close(true);resetDodgeStage();resetPuzzleStage();resetSoulStage();}
  window.addEventListener('keyup',e=>keyUp(e.key.toLowerCase()));window.PhoneMiniGames={update,toggle,close,reset,keyDown,keyUp};
})();
